# Database Examiner

This module is a test module used to open and examine database table contents to make sure data is being stored and retrieved properly

In [ ]:
import os
import pandas as pd

from local_db import DatabaseManager, DatabaseFile

from budgy.utils.file_utils import EDirectories
from budgy.database_modules.models.transactions import TransactionsTable, UpdatesTable

In [ ]:
database_file = DatabaseFile(EDirectories.DB_FILENAME, EDirectories.DB_DIR)
transactions_table_manager = DatabaseManager(TransactionsTable, database_file)
updates_table_manager = DatabaseManager(UpdatesTable, database_file)

TEST_DB_DIR = os.path.join(os.getcwd(), "tests", "test_databases")
TEST_DB_FILENAME = "test_database.db"
test_database_file = DatabaseFile(TEST_DB_FILENAME, TEST_DB_DIR)
test_transactions_table_manager = DatabaseManager(TransactionsTable, test_database_file)
test_updates_table_manager = DatabaseManager(UpdatesTable, test_database_file)

2026-03-06 17:34:00,755 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db...
2026-03-06 17:34:00,756 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db)...
2026-03-06 17:34:00,757 - local_db.database_manager - INFO - DatabaseManager session started with table: transactions
2026-03-06 17:34:00,757 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db...
2026-03-06 17:34:00,758 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db)...
2026-03-06 17:34:00,758 - local_db.database_manager - INFO - DatabaseManager session started with table: transaction_updates
2026-03-06 17:34:00,760 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db...
2026-03-06 17:34:00,760 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db)...
2026-03-06 17:34:00,760 - local_db.database_manager - INFO - DatabaseManager session started with table: transactions
2026-03-06 17:34:00,761 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db...
2026-03-06 17:34:00,761 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db)...
2026-03-06 17:34:00,761 - local_db.database_manager - INFO - DatabaseManager session started with table: transaction_updates

In [3]:
# transactions_table_manager.file.delete()
# test_transactions_table_manager.file.delete()

In [4]:
transactions_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, authorized_date, posted_date, status, account_name, description, primary_category, detailed_category, amount, repayment, exclude, base_hash, uq_hash]
Index: []

In [5]:
updates_table_manager.to_dataframe().head()

   id  timestamp                                           filepath    status
0   1 2024-01-01  /Users/eliasrodkey/git_repo/budgy_2.0/tests/te...  Complete

In [6]:
test_transactions_table_manager.to_dataframe().head()

,id,authorized_date,posted_date,status,account_name,description,primary_category,detailed_category,amount,repayment,exclude,base_hash,uq_hash
0,1,2025-12-30,2025-12-30,Posted,Checking - 9631,PayPal,Transfers,Other transfers,-25.81,False,False,47fd5c34680a9c0634f1d01fdd9894119e0f00e74bf593...,c1b52734c0b4713a12d7c46ae7f811c2b31f9476ed4abf...
1,2,2025-12-30,2025-12-30,Posted,Checking - 9631,Wells Fargo Bilt Mastercard,Transfers,Other transfers,-3808.26,False,False,305fe1a7c602b78e258b838c0737d392b019c1a7b8d010...,2108966e896d3233ca4b4012738fb7273c73ebebfbc8d3...
2,3,2025-12-30,2025-12-30,Unchecked,Savings - 7571,Direct Deposit,Income,Other income,2304.42,False,False,777d9aeba1c1fe9a0fe7d7f2543ab9f1ebd36b4fe60245...,4f876c987eb1903483b7461e357f269c8421de9590c68c...
3,4,2025-12-30,2025-12-30,Posted,Personal Profile,Connor Grady Second Place,Transfers,Account transfers,-25.00,False,False,142dac0e8d447e0ab758799899267cdef029874a770962...,88cbdb8e3da22b06137431a9ce03b09031b28f688a4120...
4,5,2025-12-30,2025-12-30,Posted,Personal Profile,Adam Greger First Place,Transfers,Account transfers,-225.00,False,False,e2d7afb69d325ff0e2d6f97cfbff99420ae8476df78a04...,7bb0a6a3c83ea0f9d66e9a9cf080da0678dc141626cdef...

In [ ]:
from budgy.utils.db_utils import upload_csv_to_db
from budgy.utils.file_utils import get_csv_filenames

TEST_CSV_DIR = os.path.join(os.getcwd(), "tests", "test_csv_download_files")
csvs = get_csv_filenames(TEST_CSV_DIR)

upload_csv_to_db(csvs[-1], transactions_db_manager=test_transactions_table_manager, updates_db_manager=test_updates_table_manager)

In [7]:
from budgy.analysis.db_query import retrieve_records_by_attribute_over_period

record_df = retrieve_records_by_attribute_over_period(12, 2025, db_manager=test_transactions_table_manager)

record_df.head()

,id,authorized_date,posted_date,status,account_name,description,primary_category,detailed_category,amount,repayment,exclude,base_hash,uq_hash
0,1,2025-12-30,2025-12-30,Posted,Checking - 9631,PayPal,Transfers,Other transfers,-25.81,False,False,47fd5c34680a9c0634f1d01fdd9894119e0f00e74bf593...,c1b52734c0b4713a12d7c46ae7f811c2b31f9476ed4abf...
1,2,2025-12-30,2025-12-30,Posted,Checking - 9631,Wells Fargo Bilt Mastercard,Transfers,Other transfers,-3808.26,False,False,305fe1a7c602b78e258b838c0737d392b019c1a7b8d010...,2108966e896d3233ca4b4012738fb7273c73ebebfbc8d3...
2,3,2025-12-30,2025-12-30,Unchecked,Savings - 7571,Direct Deposit,Income,Other income,2304.42,False,False,777d9aeba1c1fe9a0fe7d7f2543ab9f1ebd36b4fe60245...,4f876c987eb1903483b7461e357f269c8421de9590c68c...
3,4,2025-12-30,2025-12-30,Posted,Personal Profile,Connor Grady Second Place,Transfers,Account transfers,-25.00,False,False,142dac0e8d447e0ab758799899267cdef029874a770962...,88cbdb8e3da22b06137431a9ce03b09031b28f688a4120...
4,5,2025-12-30,2025-12-30,Posted,Personal Profile,Adam Greger First Place,Transfers,Account transfers,-225.00,False,False,e2d7afb69d325ff0e2d6f97cfbff99420ae8476df78a04...,7bb0a6a3c83ea0f9d66e9a9cf080da0678dc141626cdef...

In [ ]:
primary_category_report = record_df.groupby(TransactionsTable.primary_category.name)[TransactionsTable.amount.name].sum().reset_index()
detailed_category_report = record_df.groupby(TransactionsTable.detailed_category.name)[TransactionsTable.amount.name].sum().reset_index()

primary_category_report.primary_category.str
# category_report.rename(columns={TransactionsTable.amount.name: "total_amount"}, inplace=True)
# primary_category_report
# detailed_category_report

# Seperate function which can be used on both primary and detailed category reports
primary_category_report.primary_category = primary_category_report.primary_category.str.strip()
primary_category_report.primary_category = primary_category_report.primary_category.str.lower()
primary_category_report.primary_category = primary_category_report.primary_category.str.replace(" ", "_")
primary_category_report.primary_category = primary_category_report.primary_category.str.replace("&", "and")

# primary_category_report.columns = ["category", "total"]
# primary_category_report

detailed_category_report.columns = ["category", "total"]
detailed_category_report

                     category    total
0           Account transfers -1807.81
1      Clothing & accessories  -475.53
2                Coffee shops    -6.22
3        Credit card payments  4174.27
4            Digital services  -167.86
5         Events & recreation  -176.70
6                     Fitness   -75.28
7                       Games   -33.08
8                       Gifts  -164.84
9                   Groceries  -189.48
10            Interest charge   -38.81
11              Liquor stores   -32.05
12      Loans & cash advances   360.61
13                Movies & TV   -69.00
14              Music & audio   -11.99
15         Other food & drink   -33.86
16    Other health & wellness  -129.61
17  Other housing & utilities   388.20
18               Other income  7183.27
19            Other transfers -9679.49
20            Parking & tolls    -2.59
21                   Pharmacy   -44.51
22           Phone & internet   -33.96
23             Public transit   -47.88
24         Restaurants & bars  -996.51

In [36]:
# Looks like "Account transfers" contains credit card transaction doubles as well as a lot of venmo transactions, 
# will have to pay close attention here as they don't show up in regular spending charts

# Excluded cateogries of spending
#   - Overdraft Protection Transfer: (description) Transfers - Other transfers
#   - Account transfers: (detailed category) should only have tranfers from one of my accounts to another. Should evaluate to 0 anyways?
#   - ATM Withdrawl: (description) should be considered Transfers - Cash withdrawls

# Other categories to check:
#   - Debt payments
#   - 
# Start at jan 30 next time
# record_df[(record_df.detailed_category == "Account transfers") & (record_df.amount < 0)]
record_df[(record_df.detailed_category == "Loans & cash advances")]

,id,authorized_date,posted_date,status,account_name,description,primary_category,detailed_category,amount,repayment,exclude,base_hash,uq_hash
52,53,2025-12-15,2025-12-15,Unchecked,Prime Visa ***6239,Credit Card Payment,Transfers,Loans & cash advances,360.61,False,False,7fc4fc7728fd23487337bdd4d2fe191c72f5daf696ce5e...,aa1e93a6781dc97be3891c2c84507aed14001ca7a273ea...

# Categories to Avoid

* We can safely ignore **account transfers**, although I need to go through and make sure there aren't any hidden transactions in that category, venmo's tend to slip in here pretty often.
* **credit card payments** is another one that we can leave out entirely, it is paying off my credit cards. Maybe I can use this to make sure my balance is zero each month in the future?
* **investment transfers** is moving from one of my accounts to another, could be good to track what percent of takehome I am putting towards personal investments but can exclude from spending calculation
* **savings transfers** can be safely excluded

In [ ]:
# This is not that simple! will have to pass this df into anothr funcrion that can spit out our spend, income and net gain / loss

total_monthly_spend = primary_category_report.amount.sum()

np.float64(-2110.7099999999996)

In [ ]:
test_updates_table_manager.to_dataframe().head()