# Database Examiner

This module is a test module used to open and examine database table contents to make sure data is being stored and retrieved properly

In [ ]:
import os

from local_db import DatabaseManager, DatabaseFile

from budgy.utils.file_utils import EDirectories
from budgy.utils.db_models import TransactionsTable, UpdatesTable

In [6]:
database_file = DatabaseFile(EDirectories.DB_FILENAME, EDirectories.DB_DIR)
transactions_table_manager = DatabaseManager(TransactionsTable, database_file)
updates_table_manager = DatabaseManager(UpdatesTable, database_file)

TEST_DB_DIR = os.path.join(os.getcwd(), "tests", "test_utils", "test_database")
TEST_DB_FILENAME = "test_database.db"
test_database_file = DatabaseFile(TEST_DB_FILENAME, TEST_DB_DIR)
test_transactions_table_manager = DatabaseManager(TransactionsTable, test_database_file)
test_updates_table_manager = DatabaseManager(UpdatesTable, test_database_file)

2026-02-23 12:41:17,820 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db...
2026-02-23 12:41:17,821 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db)...
2026-02-23 12:41:17,821 - local_db.database_manager - INFO - DatabaseManager session started with table: transactions
2026-02-23 12:41:17,825 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db...
2026-02-23 12:41:17,826 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db)...
2026-02-23 12:41:17,826 - local_db.database_manager - INFO - DatabaseManager session started with table: transaction_updates
2026-02-23 12:41:17,834 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db...
2026-02-23 12:41:17,836 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db)...
2026-02-23 12:41:17,836 - local_db.database_manager - INFO - DatabaseManager session started with table: transactions
2026-02-23 12:41:17,839 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db...
2026-02-23 12:41:17,840 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/tests/test_utils/test_database/test_database.db)...
2026-02-23 12:41:17,840 - local_db.database_manager - INFO - DatabaseManager session started with table: transaction_updates

In [7]:
# transactions_table_manager.file.delete()
# test_transactions_table_manager.file.delete()

In [8]:
transactions_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, authorized_date, posted_date, status, account_name, description, primary_category, detailed_category, amount, repayment, exclude, base_hash, uq_hash]
Index: []

In [9]:
updates_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, timestamp, filepath, status]
Index: []

In [12]:
test_transactions_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, authorized_date, posted_date, status, account_name, description, primary_category, detailed_category, amount, repayment, exclude, base_hash, uq_hash]
Index: []

In [11]:
test_updates_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, timestamp, filepath, status]
Index: []