# Database Examiner

This module is a test module used to open and examine database table contents to make sure data is being stored and retrieved properly

In [6]:
import os

from local_db import DatabaseManager, DatabaseFile

from budgy.utils.file_utils import EDirectories
from budgy.utils.db_utils import TransactionsTable, UpdatesTable

In [13]:
database_file = DatabaseFile(EDirectories.DB_FILENAME, EDirectories.DB_DIR)
transactions_table_manager = DatabaseManager(TransactionsTable, database_file)
updates_table_manager = DatabaseManager(UpdatesTable, database_file)

TEST_DB_DIR = os.path.join(os.getcwd(), "tests", "test_database")
TEST_DB_FILENAME = "test_database.db"
test_database_file = DatabaseFile(TEST_DB_FILENAME, TEST_DB_DIR)
test_transactions_table_manager = DatabaseManager(TransactionsTable, test_database_file)
test_updates_table_manager = DatabaseManager(UpdatesTable, test_database_file)

2026-02-12 09:36:49,664 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db...
2026-02-12 09:36:49,665 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db)...
2026-02-12 09:36:49,666 - local_db.database_manager - INFO - DatabaseManager session started with table: transactions
2026-02-12 09:36:49,671 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db...
2026-02-12 09:36:49,671 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/data/databases/budgy_financial_transaction.db)...
2026-02-12 09:36:49,672 - local_db.database_manager - INFO - DatabaseManager session started with table: transaction_updates
2026-02-12 09:36:49,674 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/tests/test_database/test_database.db...
2026-02-12 09:36:49,674 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/tests/test_database/test_database.db)...
2026-02-12 09:36:49,674 - local_db.database_manager - INFO - DatabaseManager session started with table: transactions
2026-02-12 09:36:49,675 - local_db.database_connections - INFO - Creating connection engine to /Users/eliasrodkey/git_repo/budgy_2.0/tests/test_database/test_database.db...
2026-02-12 09:36:49,676 - local_db.database_connections - INFO - Creating session for Engine(sqlite:////Users/eliasrodkey/git_repo/budgy_2.0/tests/test_database/test_database.db)...
2026-02-12 09:36:49,676 - local_db.database_manager - INFO - DatabaseManager session started with table: transaction_updates

In [14]:
transactions_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, authorized_date, posted_date, status, account_name, description, primary_category, detailed_category, amount, repayment, exclude]
Index: []

In [15]:
updates_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, timestamp, filename, status]
Index: []

In [16]:
test_transactions_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, authorized_date, posted_date, status, account_name, description, primary_category, detailed_category, amount, repayment, exclude]
Index: []

In [17]:
test_updates_table_manager.to_dataframe().head()

Empty DataFrame
Columns: [id, timestamp, filename, status]
Index: []